server:
  port:8080
person:
  id: 1
  name: 张三
  hobby:
    - play
    - read
    - sleep
  family: [father,mother]
#  map:
#    k1: v1
#    k2: v2
  map: { k1: v1,k2: v2 }

  pet: {type: cat,name: ww}

student:
  name: 王二

#切换配置环境
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10485760  #请求的文件大小限制为10M
      max-request-size: 10485760